sudo: required
language: go
go_import_path: github.com/redhat-cop/quay-operator
go:
- "1.12"

env:
  - GO111MODULE=on

before_install:
  - travis_retry go mod vendor -v

deploy:
  - provider: script
    skip_cleanup: true
    script: make travis-latest-deploy
    on:
      repo: redhat-cop/quay-operator
      branch: master
      tags: false
  - provider: script
    skip_cleanup: true
    script: make travis-release-deploy
    on:
      repo: redhat-cop/quay-operator
      branch: master
      tags: true
  - provider: script
    skip_cleanup: true
    script: make travis-dev-deploy DEV_TAG=$TRAVIS_COMMIT
    on:
      condition: "! -z $PUSH_LATEST_COMMIT"