introspection_addr: :8089
http_listen_addr: :8080
log_level: debug
indexer:
  connstring: host=clair-postgres port=5432 dbname=clair user=postgres password=postgres sslmode=disable 
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  connstring: host=clair-postgres port=5432 dbname=clair user=postgres password=postgres sslmode=disable 
  max_conn_pool: 100
  run: ""
  migrations: true
  indexer_addr: clair-indexer
# tracing and metrics
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent_endpoint: "localhost:6831"
    service_name: "clair"
metrics:
  name: "prometheus"
