#Most of the config options available  with Quay-operators to configure Quay and Clair are listed here, Please create secrets, storageclass and PV and update below values accordingly
#kubectl/oc create secret generic quay-database-credential --from-literal=database-username=quay --from-literal=database-password=quay --from-literal=database-root-password=quayAdmin --from-literal=database-name=quay-enterprise
#kubectl/oc create secret generic quay-super-user --from-literal=superuser-username=testuser --from-literal=superuser-password=password --from-literal=superuser-email=testuser@example.com
#kubectl/oc create secret generic quay-config-app --from-literal=config-app-password=quay
#kubectl/oc create secret generic quay-redis-password --from-literal=password=redispassword
#kubectl/oc create -f advanced_config_example_cr.yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: example-quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    superuserCredentialsSecretName: quay-super-user
    configSecretName: quay-config-app
    configHostname: example-quayecosystem-quay-enterprise.apps
    deploymentStrategy: RollingUpdate
    skipSetup: false
    registryStorage:
      persistentVolumeAccessMode:
        - ReadWriteOnce
      persistentVolumeSize: 10Gi
      persistentVolumeStorageClassName: quay-storageclass
    database:
      volumeSize: 10Gi
      credentialsSecretName: quay-database-credential
    resources:
      requests:
        memory: 1000Mi
    envVars:
      - name: DEBUGLOG
        value: "true"
  redis:
    credentialsSecretName: quay-redis-password
    imagePullSecretName: redhat-pull-secret
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
    updateInterval: "60m"
