# This will deploy Quay with Clair automatically on the url quay.app.example.com while keeping the configuration to update it

apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    deploymentStrategy: Recreate
    skipSetup: false
    keepConfigDeployment: true
    routeHost: quay.app.example.com
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
