# Overlay variant for Project Quay "padme" release.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization	
commonAnnotations:
  quay-version: v3.4.0
bases:
  - ../../../tmp
images:
  - name: quay.io/projectquay/quay
    newName: quay.io/quay/quay
    newTag: v3.4.0-osbs
  - name: quay.io/projectquay/clair
    newName: quay.io/quay/clair
    newTag: v3.4.0-osbs
  - name: redis
    newName: registry.access.redhat.com/rhscl/redis-32-rhel7
  - name: centos/postgresql-10-centos7
    newName: registry.access.redhat.com/rhscl/postgresql-10-rhel7
    newTag: latest
