apiVersion: v1
kind: Service
metadata:
  name: quay-config-editor
  labels:
    quay-component: quay-config-editor
  annotations:
    quay-component: base
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
  selector:
    quay-component: quay-config-editor
