apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-config-editor
  labels:
    quay-component: quay-config-editor
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: quay-config-editor
  template:
    metadata:
      labels:
        quay-component: quay-config-editor
    spec:
      volumes:
        - name: config-bundle
          secret:
            secretName: quay-config-secret
        - name: extra-ca-certs
          configMap:
            name: cluster-service-ca
      containers:
        - name: quay-config-editor
          image: quay.io/projectquay/quay
          ports:
            - containerPort: 8080
              protocol: TCP
          args: ["editor", "$(QUAY_PASSWORD)", "$(QUAY_OPERATOR_ENDPOINT)"]
          env:
            - name: QUAY_CONFIG_PATH
              value: /conf/stack
            - name: QUAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quay-config-editor-credentials
                  key: password
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUAY_OPERATOR_ENDPOINT
              value: http://quay-operator:7071
            - name: QUAY_CONFIG_READ_ONLY_FIELD_GROUPS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['quay-managed-fieldgroups']
          volumeMounts:
            - name: config-bundle
              mountPath: /conf/stack
            - name: extra-ca-certs
              mountPath: /conf/stack/extra_ca_certs
