apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./clair-pg-upgrade.job.yaml
  - ./clair-pg-old.persistentvolumeclaim.yaml
  - ./clair-pg-old.deployment.yaml
components:
  - ../initialize
